### ISSUE TITLE
Error message when running "language-indexing"

### ISSUE THREAD

**Issue by d28601581** [wikitongues/Language-Indexing#26]
- Getting this error at the end of running the command "language-indexing" even when the code is running correctly.
- Happens to both Windows and MacOs.

wikipedia_site
Traceback (most recent call last):
  File "C:\Users\env\Scripts\language-indexing-script.py", line 33, in <module<>
   sys.exit(load_entry_point('language-indexing==0.0.1', 'console_scripts', 'language-indexing')())
TypeError: 'module' object is not callable

**Comment by madamc** [comment]
Can you clarify when the error happens? Is it after the crawling is completed, or does it prevent the crawling from executing?

**Comment by d28601581** [comment]
It happens after some crawling is done, not sure if that's the end of the crawling. The items.jl wrotes 21 lines before the error happend. 

After I run the command "language-indexing" a second time, the program appends the same 21 lines to the items.jl but with different orders, making it 42 lines in total. Is that work as intended?

**Comment by madamc** [comment]
It looks like the wrapper that's generated for the language-indexing is complaining about the module that's getting passed in. From the setuptools wiki [here](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html#entry-points), it looks like it wants a function. @smrohrer We could refactor language-indexing to be function-oriented instead of it's script-like format, and pass in an initial function that kicks things off as the entrypoint in the setup.py file. Should we look at doing that or try to find a way to suppress the error since it seems that the crawl is still completing successfully.

**Comment by smrohrer** [comment]
I think refactoring to an entry point function is probably the right way to go, if we can make that work

**Comment by madamc** [comment]
@vivianrdu, @smrohrer  Is there an example of what entries for the 'include_languages' and 'exclude_languages' sections of the config file?

Right now I'm receiving this error:
`AttributeError: 'SectionProxy' object has no attribute 'split'`

for this line of code
`return config['include_languages'].split(",")`

**Comment by d28601581** [comment]
Take a look at the pull request I just made, it should resolve the bug

**Comment by madamc** [comment]
@d28601581 Looks good. I'll make sure to merge with main when the pull request is merged.

**Comment by smrohrer** [comment]
Closing because this issue has been resolved on the main branch
